#!/usr/bin/env bash

if [ ! -z "$WWWUSER" ]; then
    usermod -u $WWWUSER sail
fi

if [ ! -d /.composer ]; then
    mkdir /.composer
fi

chmod -R ugo+rw /.composer

if [ "$APP_ENV" == "production" ]; then
    php artisan config:cache
    php artisan route:cache
    php artisan view:cache
fi

if [ $# -gt 0 ];then
    exec gosu $WWWUSER "$@"
else

    /usr/bin/supervisord -c /etc/supervisor/conf.d/supervisord.conf
fi
