#!/usr/bin/env bash

if [ ! -d /.composer ]; then
    mkdir /.composer
fi

chmod -R ugo+rw /.composer

if [ "$APP_ENV" == "production" ]; then
    php artisan config:cache
    php artisan route:cache
    php artisan view:cache

    php artisan migrate --force
fi

/usr/bin/supervisord -c /etc/supervisor/conf.d/supervisord.conf
