# This is a basic workflow to help you get started with Actions

name: Create AKS

# Controls when the action will run.
on:
  workflow_dispatch:

env:
  RESOURCE_GROUP: pigvelop
  CLUSTER_NAME: pigvelopAKS

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Perform a Azure Login
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Create resource group
        uses: Azure/cli@1.0.4
        with:
          inlineScript: az group create --name $RESOURCE_GROUP --location eastus

      - name: Create AKS cluster
        uses: Azure/cli@1.0.4
        with:
          inlineScript: az aks create --resource-group $RESOURCE_GROUP --name $CLUSTER_NAME --node-count 1 --enable-addons monitoring --generate-ssh-keys
