# This is a basic workflow to help you get started with Actions

name: 99 - Delete AKS Cluster (On-Demand)

# Controls when the action will run.
on:
  workflow_dispatch:

env:
  RESOURCE_GROUP: pigvelop
  CLUSTER_NAME: pigvelopAKS

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Perform a Azure Login
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Delete AKS cluster
        uses: Azure/cli@1.0.4
        with:
          inlineScript: az aks delete --resource-group $RESOURCE_GROUP --name $CLUSTER_NAME --yes
