# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Login against a Docker registry
      - name: Docker Login
        # You may pin to the exact commit or the version.
        # uses: docker/login-action@f3364599c6aa293cdc2b8391b1b56d0c30e45c8a
        uses: docker/login-action@v1.8.0
        with:
          # Username used to log against the Docker registry
          username: ${{ secrets.DOCKER_USERNAME }}
          # Password or personal access token used to log against the Docker registry
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build and push docker image
      - run: |
          docker build -t caiquebb/laravel-todo:${{ github.sha }} -f docker/Dockerfile.prod .
          docker push caiquebb/laravel-todo:${{ github.sha }}

      # Set Azure AKS config
      - name: Kubernetes set context
        uses: Azure/k8s-set-context@v1
        with:
          # Kubernetes Config
          kubeconfig: ${{ secrets.PIGVELOP_AKS_KUBECONFIG }}

      # Deploy to AKS
      - name: Deploy to Kubernetes cluster
        uses: Azure/k8s-deploy@v1.3
        with:
          # Choose the target Kubernetes namespace. If the namespace is not provided, the commands will run in the default namespace.
          namespace: ingress-basic
          # Path to the manifest files which will be used for deployment.
          manifests: |
              k8s/deploy.yml
              k8s/service.yml
          images: |
              caiquebb/laravel-todo:${{ github.sha }}
