name: Laravel ToDo Test

on: push

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    container: caiquebb/php80-laravel:latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Dependencies
        run: composer install

      - name: Configure Application
        run: |
          cp .env.example .env
          php artisan key:generate

      - name: Compile assets
        run: |
          npm install
          npm run prod

      - name: Run Laravel ToDo Test
        run: php artisan test
