name: Laravel ToDo CI /CD

on:
  push:
    branches:
      - master

  workflow_dispatch:

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    container: caiquebb/php80-laravel:latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Dependencies
        run: composer install

      - name: Configure Application
        run: |
          cp .env.example .env
          php artisan key:generate

      - name: Compile assets
        run: |
          npm install
          npm run prod

      - name: Run Laravel ToDo Tests
        run: php artisan test

  build:
    name: Build Docker Image
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v2

      - name: Docker Login
        uses: docker/login-action@v1.8.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker Build and Push
        run: |
          docker build -t caiquebb/laravel-todo:${{ github.sha }} -f docker/prod/Dockerfile .
          docker push caiquebb/laravel-todo:${{ github.sha }}

  deploy:
    name: Deploy to AKS
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2

      - name: Kubernetes set context
        uses: Azure/k8s-set-context@v1
        with:
          kubeconfig: ${{ secrets.PIGVELOP_AKS_KUBECONFIG }}

      - name: Deploy to Kubernetes cluster
        uses: Azure/k8s-deploy@v1.3
        with:
          namespace: pigvelop
          manifests: |
              k8s/deploy.yml
              k8s/service.yml
          images: |
              caiquebb/laravel-todo:${{ github.sha }}
